services:
  frontend:
    image: nginx
    container_name: frontend
    depends_on:
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/usr/share/nginx/html:ro

  server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: coffee_follower
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://user:MyStrongPassword@database:5432/coffee
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - path: ./src
          action: rebuild
    volumes:
      - logs:/app/logs

  database:
    image: postgres:16-alpine3.20
    container_name: database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d coffee -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=MyStrongPassword
      - POSTGRES_USER=user
      - POSTGRES_DB=coffee

  promtail:
    image: grafana/promtail:3.2.1
    container_name: promtail
    depends_on:
      - loki
    ports:
      - 9080:9080
    volumes:
      - logs:/var/log:ro
      - ./promtail/promtail-config.yaml:/mnt/config/promtail-config.yaml:ro
    command:
      - --config.file=/mnt/config/promtail-config.yaml

  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    ports:
      - 3100:3100
      
  grafana:
    image: grafana/grafana:11.5.1
    container_name: grafana
    ports:
      - 3000:3000

volumes:
  logs: